#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  # Quote the value: the runbook `source`s this file, and values like MAIL_FROM
  # carry spaces and angle brackets that would parse as redirection otherwise.
  local escaped="${value//\'/\'\\\'\'}"
  printf "%s='%s'\n" "$key" "$escaped" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# bc-codes OP1 provisioning wizard. Companion to docs/ultron/deploy-runbook.md:
# this script creates/captures everything EXTERNAL (Cloudflare token + account,
# D1 + R2, Resend account + domain + key, DNS records); the runbook then deploys
# with those values. Everything mutative asks first; nothing here deploys.
# Values land in .deploy.env (gitignored) which the runbook sources.

[[ -f wrangler.jsonc ]] || { echo "Run from the bc-codes repo root (wrangler.jsonc not found here)."; exit 1; }
# Unconditional on purpose: the library's `${ENV_FILE:-.env}` default above has
# already assigned .env by this point, so a `:-` fallback here never fires.
ENV_FILE=".deploy.env"

TOTAL_STAGES=9

banner "bc-codes production provisioning (OP1)"

# ── Stage 1: Cloudflare account + API token ──────────────────────────────
stage "Cloudflare account + API token"
say "Wrangler (deploy, D1, R2) authenticates with an API token. We'll create one"
say "scoped to exactly what this project needs, and record your account id."
open_url "https://dash.cloudflare.com/login"
step "Sign in (or create a free account)."
pause "Signed in? (If you just created the account, also verify your email first.)"
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "API Tokens → Create Token → scroll to Custom Token → Get started."
step "Token name: bc-codes-deploy"
step "Permissions (Add more as needed):"
say "      Account  | Workers Scripts       | Edit"
say "      Account  | D1                   | Edit"
say "      Account  | Workers R2 Storage   | Edit"
say "      Account  | Account Settings     | Read"
say "      Zone     | DNS                  | Edit"
say "      Zone     | Workers Routes       | Edit"
say "      Zone     | Zone                 | Read"
step "Zone Resources: Include → All zones (or just your bc-codes zone)."
step "Continue to summary → Create Token → copy the token (shown once)."
ask_secret CLOUDFLARE_API_TOKEN "Paste the API token:"
step "Account id: any account page's right sidebar (or the URL after /?): copy it."
say "      e.g. https://dash.cloudflare.com/abc123def456... → abc123def456..."
ask CLOUDFLARE_ACCOUNT_ID "Paste the account id:"
write_env CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
export CLOUDFLARE_API_TOKEN CLOUDFLARE_ACCOUNT_ID

# ── Stage 2: Domains (app hostname + email sending base) ─────────────────
stage "Domains: app hostname + email sending base"
say "One Cloudflare zone serves both the app and OTP email (R2's DNS records)."
open_url "https://dash.cloudflare.com/"
step "Check your domain's zone exists and shows status Active."
note "If it is not on Cloudflare yet: Add a domain → Free plan → update the"
note "nameservers at your registrar → wait for Active, then re-run this wizard."
step "Enter the zone's root domain (e.g. example.com — no https, no subdomain)."
ask CLOUDFLARE_ZONE_ROOT "Root domain (Cloudflare zone):"
step "Hostname the app will serve from (e.g. codes.example.com)."
say "      A subdomain is best; it becomes the Custom Domain in wrangler.jsonc."
ask APP_HOSTNAME "App hostname:"
MAIL_FROM="bc-codes <noreply@${CLOUDFLARE_ZONE_ROOT}>"
say "OTP mail will be sent from: $MAIL_FROM"
write_env CLOUDFLARE_ZONE_ROOT "$CLOUDFLARE_ZONE_ROOT"
write_env APP_HOSTNAME "$APP_HOSTNAME"
write_env MAIL_FROM "$MAIL_FROM"

# ── Stage 3: Create the D1 databases ─────────────────────────────────────
stage "D1: create production + staging databases"
say "Two real Cloudflare D1 databases (plan R1: staging is where the deploy"
say "smoke + the QA1 250-burst re-run safely live). This runs wrangler for you."
if confirm "Create database 'bc-codes' (production) now?"; then
  D1_OUT=$(npx wrangler d1 create bc-codes 2>&1) || { warn "wrangler said:"; printf '%s\n' "$D1_OUT" | tail -n 5; }
  PROD_D1_ID=$(printf '%s\n' "$D1_OUT" | grep -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -n1 || true)
  if [[ -n "$PROD_D1_ID" ]]; then
    write_env PROD_D1_ID "$PROD_D1_ID"
  else
    warn "could not parse the UUID from wrangler's output."
    step "Dash → Storage & Databases → D1 → bc-codes → copy the Database ID."
    ask PROD_D1_ID "Paste the production database ID:"
    write_env PROD_D1_ID "$PROD_D1_ID"
  fi
fi
if confirm "Create database 'bc-codes-staging' now?"; then
  D1_OUT=$(npx wrangler d1 create bc-codes-staging 2>&1) || { warn "wrangler said:"; printf '%s\n' "$D1_OUT" | tail -n 5; }
  STAGING_D1_ID=$(printf '%s\n' "$D1_OUT" | grep -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -n1 || true)
  if [[ -n "$STAGING_D1_ID" ]]; then
    write_env STAGING_D1_ID "$STAGING_D1_ID"
  else
    warn "could not parse the UUID from wrangler's output."
    step "Dash → D1 → bc-codes-staging → copy the Database ID."
    ask STAGING_D1_ID "Paste the staging database ID:"
    write_env STAGING_D1_ID "$STAGING_D1_ID"
  fi
fi

# ── Stage 4: Wire the database ids into wrangler.jsonc ───────────────────
stage "Wire database ids into wrangler.jsonc"
PROD_D1_ID=$(_existing PROD_D1_ID || true)
STAGING_D1_ID=$(_existing STAGING_D1_ID || true)
if [[ -z "$PROD_D1_ID" || -z "$STAGING_D1_ID" ]]; then
  warn "missing PROD_D1_ID/STAGING_D1_ID — re-run stage 3 (they must be in $ENV_FILE)."
  SKIPPED+=("wrangler.jsonc database_id wiring (ids missing)")
elif grep -q '00000000-0000-0000-0000-000000000000\|00000000-0000-0000-0000-00000000bb02' wrangler.jsonc; then
  say "Replaces the two TODO(OP1) placeholder ids with the real UUIDs."
  if confirm "Edit wrangler.jsonc in place now?"; then
    perl -pi -e "s/00000000-0000-0000-0000-000000000000/$PROD_D1_ID/g; s/00000000-0000-0000-0000-00000000bb02/$STAGING_D1_ID/g; s/^\s*\/\/ TODO\(OP1\): replace with the real (production|staging) database UUID.*\n//" wrangler.jsonc
    grep -q "$PROD_D1_ID" wrangler.jsonc && grep -q "$STAGING_D1_ID" wrangler.jsonc \
      && note "wired: both database_ids now real in wrangler.jsonc" \
      || warn "replacement did not match — set them by hand (runbook §3)."
  fi
else
  note "wrangler.jsonc already has real database ids — nothing to do."
fi
if [[ -f .svelte-kit/cloudflare/_worker.js ]]; then
  if npx wrangler deploy --dry-run >/dev/null 2>&1 && npx wrangler deploy --dry-run --env staging >/dev/null 2>&1; then
    note "config check: wrangler deploy --dry-run green for both environments."
  else
    warn "dry-run failed — run: npm run build && npx wrangler deploy --dry-run (and check wrangler.jsonc)."
  fi
else
  note "skipped dry-run (no build yet): runbook §1 does npm run build first."
fi

# ── Stage 5: Create the R2 bucket ────────────────────────────────────────
stage "R2: create the artwork-cache bucket"
say "One bucket (bc-codes-art) holds the og:image cache; staging and production"
say "share it — it is disposable cache, never correctness-bearing state (R1)."
if confirm "Create bucket 'bc-codes-art' now?"; then
  R2_OUT=$(npx wrangler r2 bucket create bc-codes-art 2>&1) || true
  if printf '%s' "$R2_OUT" | grep -qi "already exist"; then
    note "bucket already exists — fine, moving on."
  elif printf '%s' "$R2_OUT" | grep -qi "error\|failed"; then
    warn "wrangler said:"; printf '%s\n' "$R2_OUT" | tail -n 5
    SKIPPED+=("R2 bucket bc-codes-art")
  else
    note "bucket created."
  fi
fi

# ── Stage 6: Resend account + domain ─────────────────────────────────────
stage "Resend: account + sending domain"
say "Resend sends the OTP email (committed R2). Free: 100/day, 3k/month — the"
say "app's OTP rate limits (max 80 sends/day) stay comfortably under that."
open_url "https://resend.com/signup"
step "Create an account (no card needed)."
pause "Signed up and signed in?"
open_url "https://resend.com/domains"
step "Add Domain → enter your ROOT domain: ${CLOUDFLARE_ZONE_ROOT}"
warn "the ROOT domain — NOT send.${CLOUDFLARE_ZONE_ROOT}. Resend's record set"
say "      (MX+SPF on 'send', DKIM on resend._domainkey, DMARC on _dmarc) is the"
say "      root-domain shape from the R2 research record."
step "Region: keep the default (us-east-1) → Add."
step "Leave the Records tab open — the next stage copies its values into DNS."
pause "Domain added and its Records tab visible?"

# ── Stage 7: Cloudflare DNS records (Resend's table) ─────────────────────
stage "DNS: the four Resend records in Cloudflare"
say "Add these in the ${CLOUDFLARE_ZONE_ROOT} zone. Types/names are fixed; the two"
say "region/domain-dependent values come from Resend's Records tab (stage 6)."
open_url "https://dash.cloudflare.com/?to=/:account/:zone/dns/records"
step "Record 1 — MX    · name: send                    · content: feedback-smtp.us-east-1.amazonses.com · priority 10"
step "Record 2 — TXT   · name: send                    · content: v=spf1 include:amazonses.com ~all"
step "Record 3 — TXT   · name: resend._domainkey       · content: p=… (copy the exact value from Resend's Records tab)"
step "Record 4 — TXT   · name: _dmarc                  · content: v=DMARC1; p=none; rua=mailto:dmarcreports@${CLOUDFLARE_ZONE_ROOT};"
say "Gotchas (from Resend's Cloudflare guide):"
step "Use the SHORT names above (send, not send.${CLOUDFLARE_ZONE_ROOT})."
step "Every record: Proxy status = DNS only (grey cloud) — DKIM behind the"
say "      orange cloud fails verification with Cloudflare error 1004."
step "MX priority: if 10 is already taken on the name, use 20 or 30."
step "If DKIM won't verify later: check for stray NS records on _domainkey/_dkim and remove them."
pause "All four records added?"
open_url "https://resend.com/domains"
step "Back in Resend: your domain → Verify DNS Records → wait until DKIM + SPF"
say "      show green (usually minutes)."
pause "Domain shows Verified?"

# ── Stage 8: Resend API key (sending-only) ───────────────────────────────
stage "Resend: API key (sending access only)"
say "A send-only, domain-restricted key — a leak can send mail from your domain"
say "and nothing else (R2's security rationale)."
open_url "https://resend.com/settings/api-keys"
step "Create API Key → Name: bc-codes-worker"
step "Permission: Sending access"
step "If offered a domain restriction: choose ${CLOUDFLARE_ZONE_ROOT}."
step "Add → copy the key now — it starts re_ and is shown only once."
ask_secret RESEND_API_KEY "Paste the re_… API key:"
write_env RESEND_API_KEY "$RESEND_API_KEY"

# ── Stage 9: Generate the Worker secrets ─────────────────────────────────
stage "Generate Worker secrets (staging + production)"
say "Three secrets per environment (session cookie signing, fan-email HMAC"
say "pepper, OTP-code hashing pepper), generated locally with openssl. The"
say "runbook uploads them to the Workers at the right step (§4 staging, §7"
say "production) — they are stored in $ENV_FILE, which is gitignored."
if confirm "Generate six fresh secrets with openssl rand -hex 32?"; then
  for K in STAGING_SESSION_SECRET STAGING_EMAIL_PEPPER STAGING_OTP_PEPPER \
           PROD_SESSION_SECRET PROD_EMAIL_PEPPER PROD_OTP_PEPPER; do
    V=$(openssl rand -hex 32)
    printf -v "$K" '%s' "$V"
    write_env "$K" "$V"
  done
  note "staging and production use DIFFERENT values on purpose: staging test"
  note "data must never validate against production hashes."
  say "Do NOT reuse your local .dev.vars values for production."
else
  SKIPPED+=("Worker secrets generation (runbook §4/§7 needs them in $ENV_FILE)")
fi

finish
say "Next: follow docs/ultron/deploy-runbook.md, in order, from §1."
say "It sources $ENV_FILE for every value above — nothing to re-copy."
